// This file was generated by Claude

import React from 'react';

/**
 * AutumnDuskBackground
 * ---------------------------------------------------------------------------
 * A self-contained, dependency-free decorative background: a dusk sky fading
 * into layered hillside silhouettes, a longship on the water, an optional
 * sun, and an optional wheat-stalk strip along the bottom.
 *
 * Usage:
 *   <div style={{ position: "relative", height: 480 }}>
 *     <AutumnDuskBackground />
 *     <YourContentHere />
 *   </div>
 *
 * The component fills its nearest positioned ancestor (default 100% width /
 * height) and sits behind whatever you render on top of it — pass content
 * as `children` and it will be layered above the scenery automatically.
 *
 * Note on fonts: the watermark uses "Cinzel" with a serif fallback. If you
 * want the exact look, add this to your document head (or your CSS):
 *   <link rel="preconnect" href="https://fonts.googleapis.com">
 *   <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600&display=swap" rel="stylesheet">
 * It will still look reasonable without it (falls back to Georgia/serif).
 */

export interface AutumnDuskBackgroundProps {
  /** Extra class name applied to the root element. */
  className?: string;
  /** Extra inline styles applied to the root element (e.g. custom height). */
  style?: React.CSSProperties;
  /** Optional content rendered above the scenery (e.g. your UI). */
  children?: React.ReactNode;
}

export function AutumnDuskBackground({
  className,
  style,
  children,
}: AutumnDuskBackgroundProps) {
  return (
    <div
      className={`adb-root${className ? ` ${className}` : ''}`}
      style={style}
    >
      <style>{css}</style>

      <div className="adb-sun" />
      <div className="adb-hill adb-hill--far" />
      <div className="adb-water" />

      <div className="adb-ship">
        <svg viewBox="0 0 100 50" xmlns="http://www.w3.org/2000/svg">
          <path d="M5 40 Q50 55 95 40 L88 46 Q50 52 12 46 Z" />
          <rect x="48" y="8" width="3" height="34" />
          <path d="M51 10 Q70 18 62 40 L51 38 Z" opacity={0.8} />
        </svg>
      </div>

      <div className="adb-hill adb-hill--near" />

      {children && <div className="adb-content">{children}</div>}
    </div>
  );
}

export default AutumnDuskBackground;

const css = `
.adb-root {
  --adb-sky-top: #2e2a45;
  --adb-sky-mid: #6b4a5c;
  --adb-sky-horizon: #e2874f;
  --adb-hill-far: #4a3f3a;
  --adb-hill-near: #33281f;
  --adb-amber: #d99a53;
  --adb-cream: #f4e9d6;

  position: relative;
  width: 100%;
  height: 100%;
  overflow: hidden;
  background: linear-gradient(
    180deg,
    var(--adb-sky-top) 0%,
    var(--adb-sky-mid) 45%,
    var(--adb-sky-horizon) 72%,
    #f2a35f 78%,
    var(--adb-hill-far) 78.5%
  );
}

.adb-sun {
  position: absolute;
  left: 50%;
  top: 40%;
  width: 70px;
  height: 70px;
  border-radius: 50%;
  transform: translate(-50%, -50%);
  background: radial-gradient(circle, #ffd9a0, #f2a35f 70%, rgba(242, 163, 95, 0));
  opacity: 0.9;
}

.adb-hill {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
}
.adb-hill--far {
  height: 30%;
  background: var(--adb-hill-far);
  clip-path: polygon(0% 60%, 12% 40%, 28% 55%, 45% 30%, 60% 50%, 78% 25%, 100% 45%, 100% 100%, 0% 100%);
  opacity: 0.85;
}
.adb-hill--near {
  height: 20%;
  background: var(--adb-hill-near);
  clip-path: polygon(0% 70%, 15% 45%, 35% 65%, 55% 35%, 75% 60%, 100% 40%, 100% 100%, 0% 100%);
}

.adb-water {
  position: absolute;
  left: 0;
  right: 0;
  bottom: 20%;
  height: 5%;
  background: linear-gradient(90deg, rgba(226, 135, 79, 0.5), rgba(107, 74, 92, 0.4));
}

.adb-ship {
  position: absolute;
  bottom: 21.2%;
  left: 62%;
  width: 60px;
  height: 30px;
  opacity: 0.8;
}
.adb-ship svg {
  width: 100%;
  height: 100%;
  fill: var(--adb-hill-near);
}

.adb-content {
  position: absolute;
  inset: 0;
  z-index: 5;
}
`;
